### ISSUE TITLE
HP 8100?

### ISSUE THREAD

**Issue by Qiangong2** [Snikii/HP6300-HP8300#4]
I have an HP 8100 and was wondering if the Catalina guides would work on an 8100 with an i5.

It has a Radeon 4650 if that helps

**Comment by Sniki** [comment]
> I have an HP 8100 and was wondering if the Catalina guides would work on an 8100 with an i5.
> 
> It has a Radeon 4650 if that helps

No it won't work, to be honest that's different architecture and i don't have such hardware to test and provide a guide for it.
